# Generated by Django 2.2.6 on 2022-07-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export_celery', '0007_auto_20210210_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportjob',
            name='attach_file_in_mail',
            field=models.BooleanField(default=True, verbose_name='Attach the file in the email this export job is complete'),
        ),
    ]
